FROM debian:12-slim 

# Install the required packages
RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    ninja-build \
    libncurses5-dev \
    libncursesw5-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
